# Generated by Django 4.2.3 on 2023-07-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_company_company_student_name_alter_company_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobselection',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobselection',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='jobs_applied',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobSelection',
        ),
    ]
