# Generated by Django 4.2.3 on 2023-07-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_job_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobselection',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobselection',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='saved_jobs',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobSelection',
        ),
    ]
