# Generated by Django 4.2.3 on 2023-07-15 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_jobselection_job_remove_jobselection_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('job_desc', models.TextField()),
                ('job_type', models.CharField(max_length=50)),
                ('salary', models.FloatField(null=True)),
                ('location', models.CharField(null=True)),
                ('duration', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Under Review', max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='applicants',
            field=models.ManyToManyField(through='app.JobSelection', to='app.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='jobs_applied',
            field=models.ManyToManyField(through='app.JobSelection', to='app.job'),
        ),
    ]
