# Generated by Django 4.2.3 on 2023-07-16 06:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_student_saved_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='saved_jobs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
